[workspace]
members = [
  "node",
  "node/cli",
  "node/service",
  "pallets/*",
  "runtime/*",
  "common/helpers",
]
resolver = "2"

[workspace.dependencies]
log = { version = "0.4.17", default-features = false }
env_logger = "0.10.0"
twox-hash = { version = "1.6.3", default-features = false, features = [
  "digest_0_10",
] }
thiserror = "1.0.40"
apache-avro = { version = "0.14.0", default-features = false }
rand = "0.8.5"
parking_lot = "0.12.1"

# substrate wasm
parity-scale-codec = { version = "3.6.12", default-features = false }
frame-benchmarking = { version = "30.0.0", default-features = false }
frame-executive = { version = "30.0.0", default-features = false }
frame-support = { version = "30.0.0", default-features = false }
# frame-support = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.8.0", default-features = false }
frame-system = { version = "30.0.0", default-features = false }
frame-system-benchmarking = { version = "30.0.0", default-features = false }
frame-system-rpc-runtime-api = { version = "28.0.0", default-features = false }
frame-try-runtime = { version = "0.36.0", default-features = false }
sp-api = { version = "28.0.0", default-features = false }
sp-core = { version = "30.0.0", default-features = false }
sp-io = { version = "32.0.0", default-features = false }
sp-runtime = { version = "33.0.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }
sp-session = { version = "29.0.0", default-features = false }
sp-weights = { version = "29.0.0", default-features = false }
sp-offchain = { version = "28.0.0", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = [
  "derive",
] }
sp-keystore = { version = "0.36.0", default-features = false }
sp-keyring = { version = "33.0.0", default-features = false }
sp-version = { version = "31.0.0", default-features = false }
chrono = { version = "0.4.24" }
pretty_assertions = { version = "1.3.0" }
smallvec = "1.11.0"
numtoa = "0.2.4"
enumflags2 = "0.7.7"
serde = { version = "1.0", default-features = false }
serial_test = { version = "0.9.0", default-features = false }
base64-url = { version =  "3.0.0", default-features = false }
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa"] }

# substrate pallets
pallet-aura = { version = "29.0.0", default-features = false }
pallet-authorship = { version = "30.0.0", default-features = false }
pallet-balances = { version = "30.0.0", default-features = false }
pallet-collective = { version = "30.0.0", default-features = false }
pallet-democracy = { version = "30.0.0", default-features = false }
pallet-multisig = { version = "30.0.0", default-features = false }
pallet-preimage = { version = "30.0.0", default-features = false }
pallet-scheduler = { version = "31.0.0", default-features = false }
pallet-session = { version = "30.0.0", default-features = false }
pallet-sudo = { version = "30.0.0", default-features = false }
pallet-timestamp = { version = "29.0.0", default-features = false }
pallet-transaction-payment = { version = "30.0.0", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "30.0.0", default-features = false }
pallet-treasury = { version = "29.0.0", default-features = false }
pallet-utility = { version = "30.0.0", default-features = false }
pallet-proxy = { version = "30.0.0", default-features = false }

# polkadot
polkadot-cli = { version = "9.0.0" }
polkadot-parachain-primitives = { version = "8.0.0", default-features = false }
polkadot-runtime-common = { version = "9.0.0", default-features = false }
polkadot-primitives = { version = "9.0.0" }
polkadot-service = { version = "9.0.0" }

# cumulus
cumulus-client-cli = { version = "0.9.0" }
cumulus-client-collator = { version = "0.9.0" }
cumulus-client-consensus-aura = { version = "0.9.0" }
cumulus-client-consensus-common = { version = "0.9.0" }
cumulus-client-consensus-proposer = { version = "0.9.0" }
cumulus-client-network = { version = "0.9.0" }
cumulus-client-service = { version = "0.9.0" }
cumulus-relay-chain-inprocess-interface = { version = "0.9.0" }
cumulus-relay-chain-interface = { version = "0.9.0" }
cumulus-relay-chain-minimal-node = { version = "0.9.0" }
cumulus-relay-chain-rpc-interface = { version = "0.9.0" }

cumulus-pallet-aura-ext = { version = "0.9.0", default-features = false }
cumulus-pallet-parachain-system = { version = "0.9.0", default-features = false }
cumulus-pallet-session-benchmarking = { version = "11.0.0", default-features = false }
cumulus-primitives-aura = { version = "0.9.0", default-features = false }
cumulus-primitives-core = { version = "0.9.0", default-features = false }
cumulus-client-parachain-inherent = { version = "0.3.0" }
cumulus-primitives-timestamp = { version = "0.9.0", default-features = false }
pallet-collator-selection = { version = "11.0.1", default-features = false }
parachain-info = { version = "0.9.0", package = "staging-parachain-info", default-features = false }

# client
derive_more = "0.99.17"
futures = "0.3.25"
hex = { version = "0.4.3", default-features = false }
hex-literal = "0.4.1"
impl-serde = { version = "0.4.0", default-features = false }
jsonrpsee = { version = "0.22.5", default-features = false }
oorandom = "11.1.3"
phf = { version = "0.11", default-features = false, features = ["macros"] }
rayon = "1.5.3"
serde_json = { version = "1.0.86", default-features = false }
tokio = { version = "1.25.0", default-features = false }
unicode-normalization = { version = "0.1.22", default-features = false }
clap = { version = "4.2.5", features = ["derive"] }

frame-benchmarking-cli = { version = "34.0.0" }
pallet-transaction-payment-rpc = { version = "32.0.0" }
sc-basic-authorship = { version = "0.36.0" }
sc-chain-spec = { version = "29.0.0" }
sc-cli = { version = "0.38.0" }
sc-client-api = { version = "30.0.0" }
sc-client-db = { version = "0.37.0" }
sc-consensus = { version = "0.35.0" }
sc-consensus-manual-seal = { version = "0.37.0" }
sc-executor = { version = "0.34.0", default-features = false }
sc-keystore = { version = "27.0.0" }
sc-network = { version = "0.36.0" }
sc-network-common = { version = "0.35.0" }
sc-network-sync = { version = "0.35.0" }
sc-offchain = { version = "31.0.0" }
sc-rpc = { version = "31.0.0" }
sc-service = { version = "0.37.0" }
sc-sysinfo = { version = "29.0.0" }
sc-telemetry = { version = "17.0.0" }
sc-tracing = { version = "30.0.0" }
sc-transaction-pool = { version = "30.0.0" }
sc-transaction-pool-api = { version = "30.0.0" }
sp-block-builder = { version = "28.0.0", default-features = false }
sp-blockchain = { version = "30.0.0", default-features = false }
sp-consensus = { version = "0.34.0" }
sp-consensus-aura = { version = "0.34.0", default-features = false }
sp-genesis-builder = { version = "0.9.0", default-features = false }
sp-inherents = { version = "28.0.0", default-features = false }
sp-rpc = { version = "28.0.0", default-features = false }
sp-timestamp = { version = "28.0.0" }
sp-transaction-pool = { version = "28.0.0", default-features = false }
sp-wasm-interface = { version = "20.0.0" }
sp-metadata-ir = { version = "0.6.0" }
substrate-build-script-utils = { version = "11.0.0" }
substrate-test-utils = { version = "3.0.0" }

substrate-frame-rpc-system = { version = "30.0.0" }
substrate-prometheus-endpoint = { version = "0.17.0" }
try-runtime-cli = { version = "0.40.0" }

[profile.release]
panic = "unwind"
lto = true
codegen-units = 1
strip = true

[profile.production]
inherits = "release"

# Faster build for bench-dev
[profile.bench-dev]
inherits = "release"
strip = false
codegen-units = 16
lto = false
